#!/usr/bin/env bash
# This script installs HAProxy on a new ubuntu machine and configures
# it to distribute web traffic between two servers

sudo apt-get update -y

# Install HAProxy 2.9
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.9 -y
sudo apt-get install haproxy=2.9.\* -y

# Configure HAProxy
echo "frontend myfrontend
    bind *:80
    mode http
    default_backend mybackend
backend mybackend
    balance roundrobin
    server web-01 100.26.120.194:80 check
    server web-02 34.239.207.6:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg    

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
