#!/usr/bin/env bash
# This script generates a mysql dump and creates a compresssed archive
# out of it.

MYSQL_ROOT_PASSWORD=$1

# Get the current date
CURRENT_DATE=$(date +"%d-%m-%Y")

# Define the filename for the MySQL dump and the archive
DUMP_FILE="backup.sql"
ARCHIVE_FILENAME="${CURRENT_DATE}.tar.gz"

# Create a MySQL dump of all databases
sudo mysqldump -u root -p"${MYSQL_ROOT_PASSWORD}" --all-databases > "${DUMP_FILE}"

# Create a tar.gz archive of the MySQL dump
tar -czf "${ARCHIVE_FILENAME}" "${DUMP_FILE}"
